--PACKAGE SPECIFICATION
CREATE OR REPLACE PACKAGE OLDEMO
AS
   FUNCTION  addition(x NUMBER, y NUMBER) RETURN NUMBER;
   FUNCTION  addition(x NUMBER, y NUMBER, z NUMBER) RETURN NUMBER;
END;
/

--PACKAGE BODY
CREATE OR REPLACE PACKAGE BODY OLDEMO
AS
   FUNCTION  addition(x NUMBER, y NUMBER) RETURN NUMBER
   AS
   BEGIN
   RETURN x + y;
        
   END;
   FUNCTION  addition(x NUMBER, y NUMBER, z NUMBER) RETURN NUMBER
   AS
   BEGIN
   RETURN x+y+z;
   END addition;
END;
/